name: Push to Prod

on:
  push:
    branches: ['main']
    paths: 
      - app/**

permissions: 
  id-token: write
  contents: read    

env:
  AWS_REGION: eu-west-2                       

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials w/ OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
        aws-region: eu-west-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image 
      id: build-image
      run: |
        cd app
        docker build -t siada2/url-prod .
        docker tag siada2/url-prod:latest ${{ secrets.PROD_REPO }}:${{ github.sha }}

    - name: Push to Amazon ECR
      run: |
        docker push ${{ secrets.PROD_REPO }}:${{ github.sha }}

  codedeploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials w/ OIDC
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.ADMIN_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Trigger CodeDeploy Deployment
          id: deployment
          run: |
            ./codedeploy/deploy.sh
