name: Deploy to staging/testing

on:
  pull_request:
    branches: [main]

permissions: 
  id-token: write
  contents: read    

env:
  AWS_REGION: eu-west-2                       

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials w/ OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: 
        aws-region: eu-west-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image 
      id: build-image
      run: |
        cd app
        docker build -t  .
        docker tag 
        
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 

    - name: Push to Amazon ECR
      run: |
        docker push 

  terraform-apply:
    runs-on: ubuntu-24.04

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials w/ OIDC
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.ADMIN_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Run checkov scan
          uses: bridgecrewio/checkov-action@v12

        - name: Terraform apply
          run: |
            cd terraform/staging
            terraform init 
            terraform apply --auto-approve -var-file="staging.tfvars" 