name: Deploy to staging/testing

on:
  pull_request:
    branches: [main]

permissions: 
  id-token: write
  contents: read    

env:
  AWS_REGION: eu-west-2                       

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials w/ OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
        aws-region: eu-west-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image 
      id: build-image
      run: |
        cd app
        docker build -t siada2/url-staging .
        docker tag siada2/url-staging:latest ${{ secrets.STAGING_REPO }}:latest
        
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        image-ref: ${{ secrets.DEV_REPO }}:latest

    - name: Push to Amazon ECR
      run: |
        docker push ${{ secrets.STAGING_REPO }}:latest

  deploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials w/ OIDC
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.ADMIN_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Run checkov scan
          uses: bridgecrewio/checkov-action@v12
          continue-on-error: true

        - name: Terraform apply
          uses: dflook/terraform-apply@v2
          with:
            path: terraform/staging
            auto_approve: true